In [14]:
import numpy as np
import pandas as pd

# Sample categorical data
data = ['apple', 'banana', 'cherry', 'date', 'apple', 'cherry']

# Convert to pandas DataFrame
df = pd.DataFrame(data, columns=['fruit'])

# Perform one-hot encoding using pandas get_dummies
one_hot_encoded = pd.get_dummies(df['fruit'])

print("One-Hot Encoded DataFrame:")
print(one_hot_encoded)

One-Hot Encoded DataFrame:
   apple  banana  cherry   date
0   True   False   False  False
1  False    True   False  False
2  False   False    True  False
3  False   False   False   True
4   True   False   False  False
5  False   False    True  False


In [15]:
from sklearn.preprocessing import OneHotEncoder

# Sample categorical data
data = ['apple', 'banana', 'cherry', 'date', 'apple', 'cherry']

# Reshape the data to fit the encoder
data = np.array(data).reshape(-1, 1)

# Initialize the OneHotEncoder
encoder = OneHotEncoder(sparse_output=False)

# Perform one-hot encoding
one_hot_encoded = encoder.fit_transform(data)

print("One-Hot Encoded Array:")
print(one_hot_encoded)


One-Hot Encoded Array:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]]


In [16]:
from numpy import array
from numpy import argmax
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
# define example
data = ['Tiger','Cheetah','Cougar','Leopard', 'Cheetah', 'Cougar', 'Panther', 'Jaguar', 'Eurasian lynx', 'Tiger']
values = array(data)
print(values)
# integer encode
label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(values)
print(integer_encoded)

['Tiger' 'Cheetah' 'Cougar' 'Leopard' 'Cheetah' 'Cougar' 'Panther'
 'Jaguar' 'Eurasian lynx' 'Tiger']
[6 0 1 4 0 1 5 3 2 6]


In [18]:
from sklearn.preprocessing import OneHotEncoder
# binary encode
onehot_encoder = OneHotEncoder(sparse_output=False,categories='auto')
integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)
onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
print(values)
print(onehot_encoded)

['Tiger' 'Cheetah' 'Cougar' 'Leopard' 'Cheetah' 'Cougar' 'Panther'
 'Jaguar' 'Eurasian lynx' 'Tiger']
[[0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]


In [ ]:
import numpy as np

def one_hot_encode(corpus):
    # Create a vocabulary of unique words
    vocabulary = sorted(set(corpus))
    word_to_index = {word: idx for idx, word in enumerate(vocabulary)}

    # Initialize a matrix for one-hot encoding
    one_hot_matrix = np.zeros((len(corpus), len(vocabulary)), dtype=int)

    # Create one-hot vectors for each word in the corpus
    for i, word in enumerate(corpus):
        one_hot_matrix[i, word_to_index[word]] = 1

    return one_hot_matrix, word_to_index

# Example usage
corpus = ["this", "is", "a", "simple", "example"]
one_hot_matrix, word_to_index = one_hot_encode(corpus)

print("Vocabulary:", word_to_index)
print("One-Hot Encoded Matrix:\n", one_hot_matrix)


Vocabulary: {'a': 0, 'example': 1, 'is': 2, 'simple': 3, 'this': 4}
One-Hot Encoded Matrix:
 [[0 0 0 0 1]
 [0 0 1 0 0]
 [1 0 0 0 0]
 [0 0 0 1 0]
 [0 1 0 0 0]]
